# Generated by Django 4.0.1 on 2022-03-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='details',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.TextField(default=None),
        ),
    ]
