# Generated by Django 4.0.1 on 2022-04-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0003_rename_customer_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_id',
        ),
        migrations.AddField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, default='exit', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
