# Generated by Django 4.0.1 on 2022-04-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_link',
        ),
        migrations.AlterField(
            model_name='article',
            name='details',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
