# Generated by Django 4.0.1 on 2022-04-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0004_remove_article_article_id_article_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
